[package]
name = "deferredborrow"
version = "0.1.0"
authors = ["Chris Fallin <cfallin@mozilla.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
